const actionTypes = Object.freeze({
  //app
  APP_START_UP_COMPLETE: "APP_START_UP_COMPLETE",
  SET_CONTENT_OF_CONFIRM_MODAL: "SET_CONTENT_OF_CONFIRM_MODAL",
  CHANGE_LANGUAGE: "CHANGE_LANGUAGE",

  //user
  ADD_USER_SUCCESS: "ADD_USER_SUCCESS",

  USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
  USER_LOGIN_FALL: "USER_LOGIN_FALL",
  PROCESS_LOGOUT: "PROCESS_LOGOUT",

  // addmin
  FETCH_GENDER_START: "FETCH_GENDER_START",
  FETCH_GENDER_SUCCESS: "FETCH_GENDER_SUCCESS",
  FETCH_GENDER_FAIDED: "FETCH_GENDER_FAIDED",

  FETCH_POSITION_SUCCESS: "FETCH_POSITION_SUCCESS",
  FETCH_POSITION_FAIDED: "FETCH_POSITION_FAIDED",

  FETCH_ROLE_SUCCESS: "FETCH_ROLE_SUCCESS",
  FETCH_ROLE_FAIDED: "FETCH_ROLE_FAIDED",

  CREATE_USER_SUCCESS: "CREATE_USER_SUCCESS",
  CREATE_USER_FAIDED: "CREATE_USER_FAIDED",

  CREATE_TOUR_SUCCESS: "CREATE_TOUR_SUCCESS",
  CREATE_TOUR_FAIDED: "CREATE_TOUR_FAIDED",

  DELETE_USER_SUCCESS: "DELETE_USER_SUCCESS",
  DELETE_USER_FAIDED: "DELETE_USER_FAIDED",

  DELETE_TOUR_SUCCESS: "DELETE_TOUR_SUCCESS",
  DELETE_TOUR_FAIDED: "DELETE_TOUR_FAIDED",

  EDIT_USER_SUCCESS: "EDIT_USER_SUCCESS",
  EDIT_USER_FAIDED: "EDIT_USER_FAIDED",

  EDIT_TOUR_SUCCESS: "EDIT_TOUR_SUCCESS",
  EDIT_TOUR_FAIDED: "EDIT_TOUR_FAIDED",

  FETCH_ALL_USER_SUCCESS: "FETCH_ALL_USER_SUCCESS",
  FETCH_ALL_USER_FAIDED: "FETCH_ALL_USER_FAIDED",

  FETCH_ALL_TOUR_SUCCESS: "FETCH_ALL_TOUR_SUCCESS",
  FETCH_ALL_TOUR_FAIDED: "FETCH_ALL_TOUR_FAIDED",

  FETCH_TOP_DOCTOR_SUCCESS: "FETCH_TOP_DOCTOR_SUCCESS",
  FETCH_TOP_DOCTOR_FAIDED: "FETCH_TOP_DOCTOR_FAIDED",

  FETCH_TOP_TOUR_SUCCESS: "FETCH_TOP_TOUR_SUCCESS",
  FETCH_TOP_TOUR_FAIDED: "FETCH_TOP_TOUR_FAIDED",

  FETCH_ALL_DOCTOR_SUCCESS: "FETCH_ALL_DOCTOR_SUCCESS",
  FETCH_ALL_DOCTOR_FAIDED: "FETCH_ALL_DOCTOR_FAIDED",

  SAVE_DETAIL_DOCTOR_SUCCESS: "SAVE_DETAIL_DOCTOR_SUCCESS",
  SAVE_DETAIL_DOCTOR_FAIDED: "SAVE_DETAIL_DOCTOR_FAIDED",
});

export default actionTypes;
